name: Build ImmortalWrt

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - cr6608-full
          - cr6608-mini

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build toolchain
        run: |
          sudo apt update
          sudo apt install -y build-essential file libncurses-dev zlib1g-dev gawk git \
            gettext libssl-dev xsltproc rsync wget unzip python3 python3-distutils
          wget --quiet https://downloads.immortalwrt.org/snapshots/targets/ramips/mt7621/immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64.tar.zst
          tar --zstd -xvf immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64.tar.zst

      - name: Parse configuration
        id: config
        run: |
          CONFIG=config/${{ matrix.target }}.config
          if [ ! -f "$CONFIG" ]; then echo "No vaild data in config, check it."; exit 1; fi
          PROFILE=$(grep '^PROFILE=' "$CONFIG" | cut -d= -f2-)
          PACKAGES=$(grep '^PACKAGES=' "$CONFIG" | cut -d= -f2-)
          echo "profile=$PROFILE" >> "$GITHUB_OUTPUT"
          echo "packages=$PACKAGES" >> "$GITHUB_OUTPUT"

      - name: Cache dl/
        uses: actions/cache@v4
        with:
          path: immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64/dl
          key: dl-${{ steps.config.outputs.profile }}

      - name: Cache build_dir/
        uses: actions/cache@v4
        with:
          path: immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64/build_dir
          key: build-${{ steps.config.outputs.profile }}-${{ matrix.target }}

      - name: Cache staging_dir/
        uses: actions/cache@v4
        with:
          path: immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64/staging_dir
          key: staging-${{ steps.config.outputs.profile }}-${{ matrix.target }}

      - name: Build image
        working-directory: immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64
        run: |
          make image PROFILE="${{ steps.config.outputs.profile }}" PACKAGES="${{ steps.config.outputs.packages }}" | tee build.log

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-firmware-${{ github.run_id }}
          path: immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64/bin/targets/ramips/mt7621/
          retention-days: 3

      - name: Upload build log (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-log-${{ github.run_id }}
          path: immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64/build.log
          retention-days: 3
