name: Build ImmortalWrt

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:
        

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: set up build toolchain
              run: |
                sudo apt update
                sudo apt install build-essential file libncurses-dev zlib1g-dev gawk git \
                    gettext libssl-dev xsltproc rsync wget unzip python3 python3-distutils    
                wget https://downloads.immortalwrt.org/snapshots/targets/ramips/mt7621/openwrt-imagebuilder-ramips-mt7621.Linux-x86_64.tar.zst
