name: Build ImmortalWrt

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:
        

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: set up build toolchain
              run: |
                sudo apt update
                sudo apt install build-essential file libncurses-dev zlib1g-dev gawk git \
                    gettext libssl-dev xsltproc rsync wget unzip python3 python3-distutils    
                wget https://downloads.immortalwrt.org/snapshots/targets/ramips/mt7621/immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64.tar.zst
                tar --zstd -xvf immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64.tar.zst                

            - name: build image
              run: |
                make image PROFILE=xiaomi_mi-router-cr6608 PACKAGES="htop kmod-nf-tproxy kmod-nft-tproxy kmod-tun bash curl ip-full ruby ruby-yaml kmod-inet-diag unzip luci-compat luci luci-base luci-i18n-base-zh-cn owut -ppp -ppp-mod-pppoe -kmod-ppp -kmod-pppoe -kmod-pppox -shellsync"

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: cr6608-firmware-${{ github.run_id }}
                path: immortalwrt-imagebuilder-ramips-mt7621.Linux-x86_64/bin/targets/ramips/mt7621/   
